
verify:
	cd src; liquid Liquid/ProofCombinators.hs && liquid Data/Proxy.hs && liquid Data/List.hs && liquid Data/List/NonEmpty.hs && liquid Data/Semigroup.hs && liquid Data/Functor.hs

build:
	stack build
